name: ulula
description: Ulula app
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  bloc: ^8.1.0
  dartz: ^0.10.1
  dio: ^4.0.6
  dotted_border: ^2.0.0+3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.17
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.2
  formz: ^0.6.0
  get_it: ^7.2.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  logger: ^1.1.0
  rxdart: ^0.27.7
  shared_preferences: ^2.0.17
  sticky_headers: ^0.3.0+2

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/img/
    - assets/icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-Regular.ttf
        - asset: assets/fonts/open-sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/open-sans/OpenSans-Bold.ttf
          weight: 700

flutter_native_splash:
  color: '#17191C'
  image: assets/img/logo.png
  android_gravity: center
  ios_content_mode: center
  android_12:
    image: assets/img/logo.png
    icon_background_color: '#17191C'
